theme: jekyll-theme-cayman
title: información, cursos, etc
author: Oswaldo Sevilla

language: en
date_format: '%Y-%m-%d'

feed:
  path: atom.xml

plugins:
 - jemoji
 - jekyll-sitemap
 - jekyll-feed

rss:


